name: Publish on JSR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - run: |
          npx jsr install --pnpm
          npx jsr publish --dry-run
          npx jsr publish
